    let data = [
    {
        id: 1,
        title: '수박',
        imgUrl: 'img/fruit1.jpg',
        weight: '5~6kg',
        content: '당도선별 프리미엄 고당도 하우스수박',
        price: 29000,
    },
    {
        id: 2,
        title: '참외',
        imgUrl: 'img/fruit2.jpg',
        weight: '3kg',
        content: '산지직송 성주 달콤참외',
        price: 16900,
    },
    {
        id: 3,
        title: '사과',
        imgUrl: 'img/fruit3.jpg',
        weight: '5kg',
        content: '고씨네농장 고당도 청송사과, 햇부사',
        price: 13000,
    },
    {
        id: 4,
        title: '바나나',
        imgUrl: 'img/fruit4.jpg',
        weight: '6kg',
        content: '델몬트 필리핀 바나나',
        price: 15000,
    },
    {
        id: 5,
        title: '딸기',
        imgUrl: 'img/fruit5.jpg',
        weight: '1박스',
        content: '설향 딸기, 킹스베리',
        price: 14500,
    },
    {
        id: 6,
        title: '오렌지',
        imgUrl: 'img/fruit6.jpg',
        weight: '4kg',
        content: '캘리포니아 네이블 오렌지',
        price: 17000,
    },
    {
        id: 7,
        title: '토마토',
        imgUrl: 'img/fruit7.jpg',
        weight: '5kg',
        content: '행복한 농부 완숙찰토마토',
        price: 20000,
    },
    {
        id: 8,
        title: '포도',
        imgUrl: 'img/fruit8.jpg',
        weight: '상세참조',
        content: '팜앤프룻 프리미엄 아삭한 애플청포도',
        price: 25000,
    },
    {
        id: 9,
        title: '망고',
        imgUrl: 'img/fruit9.jpg',
        weight: '1박스',
        content: '프리미엄 제주애플망고',
        price: 18500,
    },
    ];

    export default data;
